name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: dolfinx/real:latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cd src && python3 setup.py install
    - name: test
      run: cd test && python3 -m pytest -s -v .
