name: C/C++ CI

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:latest
    steps:
    - uses: actions/checkout@v2
    - name: install_clang
      run: pip3 install clang-format==9.0.0 && export CI=1
    - name: run_formatter_script
      run: ./scripts/run-clang-format.sh

  build:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:latest
    steps:
    - uses: actions/checkout@v2
    - name: Get eigen
      run: |
        export HOMEDIR=$PWD
        mkdir -p ~/opt/eigen && cd ~/opt/eigen 
        git clone https://gitlab.com/libeigen/eigen.git
        cd $HOMEDIR
    - name: build
      run: cd src && python3 setup.py install
    - name: test
      run: cd test && python3 -m pytest -s -v .
